-- AlterTable
ALTER TABLE "Site" ADD COLUMN     "gracePeriodMin" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "idleFeePerMinUsd" DOUBLE PRECISION NOT NULL DEFAULT 0.08,
ADD COLUMN     "pricePerKwhUsd" DOUBLE PRECISION NOT NULL DEFAULT 0.35,
ADD COLUMN     "pricingMode" TEXT NOT NULL DEFAULT 'flat',
ADD COLUMN     "touWindows" JSONB;
